// 分类名到实际目录名的映射
// key 是分类名（用于 URL 和显示）
// value 是实际的目录名
export const categoryToDirMap: Record<string, string> = {
  nestjs: "nestjs",
  devops: "devops",
  database: "database",
  "claude-code": "claude-code",
  java: "java",
  hono: "hono",
  prisma: "prisma",
  mysql: "mysql",
  docker: "docker",
  nextjs: "nextjs",
  golang: "golang",
  mongoose: "mongoose",
  typescript: "typescript",
  redis: "redis",
  mybatis: "mybatis",
  trpc: "trpc",
  typeorm: "typeorm",
  python: "python",
  agent: "agent",
  drizzle: "drizzle",
  rust: "rust",
  springboot: "springboot",
  vite: "vite",
  "nodejs-core": "nodejs-core",
  // content2 合并的分类
  "ai-fullstack": "ai-fullstack",
  agent2: "agent2",
  "claude-code2": "claude-code2",
  database2: "database2",
  devops2: "devops2",
  golang2: "golang2",
  hono2: "hono2",
  mongoose2: "mongoose2",
  mybatis2: "mybatis2",
  redis2: "redis2",
  rust2: "rust2",
  trpc2: "trpc2",
  typeorm2: "typeorm2",
  typescript2: "typescript2",
  vite2: "vite2",
  // 新系列
  langchain: "langchain",
  rag: "rag",
};

// 目录名到分类名的反向映射
export const dirToCategoryMap: Record<string, string> = {
  nestjs: "nestjs",
  devops: "devops",
  database: "database",
  "claude-code": "claude-code",
  java: "java",
  hono: "hono",
  prisma: "prisma",
  mysql: "mysql",
  docker: "docker",
  nextjs: "nextjs",
  golang: "golang",
  mongoose: "mongoose",
  typescript: "typescript",
  redis: "redis",
  mybatis: "mybatis",
  trpc: "trpc",
  typeorm: "typeorm",
  python: "python",
  agent: "agent",
  drizzle: "drizzle",
  rust: "rust",
  springboot: "springboot",
  vite: "vite",
  "nodejs-core": "nodejs-core",
  // content2 合并的分类
  "ai-fullstack": "ai-fullstack",
  agent2: "agent2",
  "claude-code2": "claude-code2",
  database2: "database2",
  devops2: "devops2",
  golang2: "golang2",
  hono2: "hono2",
  mongoose2: "mongoose2",
  mybatis2: "mybatis2",
  redis2: "redis2",
  rust2: "rust2",
  trpc2: "trpc2",
  typeorm2: "typeorm2",
  typescript2: "typescript2",
  vite2: "vite2",
  // 新系列
  langchain: "langchain",
  rag: "rag",
};
